### ISSUE TITLE
Repo and modname in topic is castles, code uses castle

### ISSUE THREAD

**Issue by rubenwardy** [Philipbenr/castles#9]
This breaks my mod manager http://rubenwardy.com/mtmods4android/

**Comment by Philipbenr** [comment]
This will become a modpack eventually. I am splitting everything up right now, so you'll just have to be patient. I will get it done... I just have too much work to deal with it right now.

**Comment by Napiophelios** [comment]
The mod.conf also needs to reflect the proper name;
It is currently 'name = castles' 
so even if you rename the folder to castle it wont start.

**Comment by Philipbenr** [comment]
Where is this mod.conf?

You are using latest Minetest, correct?

**Comment by Napiophelios** [comment]
sorry man I am new to git, I was trying to relate this to the minetest mods fork of Castles and accidentally did it here.

I finally figured out how to do a pull request in the right place.

**Comment by Philipbenr** [comment]
OK. Merged.
